<?php
require_once "header.phtml";
require_once "navAdmin.phtml";

?>

<link rel="stylesheet" href="./z.css">
<link rel="stylesheet" href="./stylesheet.css">


  <div class="container-fluid">
    <?php
    require_once "adminSideNav.phtml";

     ?>
     <br>
     <br>
                    <div class="well col-sm-6 col-sm-offset-3 bluredSection" id="addingCompany" <?php if(isset($_GET['Country']) && isset($_GET['City']) ){ echo 'style=""';} ?>>

                        <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="GET">


                            <div class="form-group">
                                <label for="Country" class="control-label">Company Name</label>
                                <input type="text" name="Country" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">Company Website</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">Town</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">County</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">Main Tier</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">Sub Tier</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">industry</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">Date_Added</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>
                            <div class="form-group">
                                <label for="City" class=" control-label">Location_id</label>
                                <input type="text" name="City" class="form-control circle">
                            </div>

                            <button type="submit" name="Fsubmit" class="btn-sm btn-info Brown center circle">Forcast for tomorrow</button>
                            <a href="./superAdmin.php" class="btn btn-sm btn-warning Brown center circle">Back to Dashboard</a>

                        </form>



                        <?php echo $view->result; ?>

                    </div>

  </div>
<style>


    #addingCompany{
      background-color: rgba(255,255,255,0.3);
    }


</style>
<?php
require_once "footer.phtml";
?>
