<?php
require_once "Header.phtml";
require_once "navAdmin.phtml";
require_once "adminSideNav.phtml";

if(empty($_GET))
{
?>


  <div class="well col-sm-6 col-sm-offset-3" id="CompanyProfile">

      <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="GET">


          <div class="form-group">
              <label for="Country" class=" control-label">Company Name</label>
              <input type="text" name="Company_name" class="form-control half" >
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Website</label>
              <input type="text" name="Company_website" class="form-control half" >
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Town</label>
              <input type="text" name="Town" class="form-control half" >
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">County</label>
              <input type="text" name="County" class="form-control half">
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Main Tier</label>
              <input type="text" name="Main_tier" class="form-control half">
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Sub Tier</label>
              <input type="text" name="Subtier" class="form-control half">
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Industry</label>
              <input type="text" name="Industry" class="form-control half">
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Date added</label>
              <input type="date" name="Date_added" class="form-control half">
          </div>
          <div class="form-group">
              <label for="City" class=" control-label">Location</label>
              <select name="" id="" class="form-control half">
                <option disabled="disabled" selected="true">choose the location from the list </option>
                <option value="">london</option>
                <option value="">Manchester</option>

              </select>
          </div>



          <button type="submit" name="Fsubmit" class="btn btn-info Brown center">Forcast for tomorrow</button>
          <a href="./Dashboard.php" class="btn btn-warning Brown center">Back to Dashboard</a>

      </form>


  </div>

  <div class="container col-xs-10 col-xs-offset-1 animated bounceInDown" <?php if (empty($_GET['Country']) && empty($_GET['City']) ){ echo 'style="display: none;';} ?>>
      <table class="table table-bordered table-responsive" id="weatherResult" style="text-align: center">
          <thead>
          <tr >
              <th scope="col">City</th>
              <th class="animated fadeInRightBig" scope="col" style="text-align: center"><?php echo "$City" ; ?></th>

          </tr>
          </thead>
          <tbody>
          <tr>
              <th scope="row">Country</th>
              <td class="animated fadeInRightBig"><?php echo "$Country" ; ?></td>

          </tr>
          <tr>
              <th scope="row">Humidity</th>
              <td class="animated fadeInRightBig"><?php echo $weatherArray['humidity'] ; ?></td>

          </tr>
          <tr>
              <th scope="row">Weather Condition</th>
              <td class="animated fadeInRightBig"><?php echo $weatherArray['weatherCondition'] ; ?></td>

          </tr>
          <tr>
              <th scope="row">Wind Speed (meter/sec)</th>
              <td class="animated fadeInRightBig"><?php echo $weatherArray['windSpeed'] ; ?></td>

          </tr>
          <tr>
              <th scope="row">Wind Direction (meteorological)</th>
              <td class="animated fadeInRightBig"><?php echo $weatherArray['windDirection'] ; ?></td>

          </tr>
          <tr>
              <th scope="row">Temperature (Kelvin)</th>
              <td class="animated fadeInRightBig"><?php echo $weatherArray['temp'] ; ?></td>

          </tr>
          <tr>
              <th scope="row"> Pressure</th>
              <td class="animated fadeInRightBig"><?php echo $weatherArray['pressure'] ; ?></td>

          </tr>
          </tbody>
      </table>
  </div>


<?php
}
require_once "footer.phtml";
?>
<script>
$(document).ready(function(){
TweenLite.fromTo($('#CompanyProfile'),3.7,{x: -500, rotationX: "-=40",rotationY: "-=30",ease: "Power4.easeOut"}, {x:0,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
});
</script>
<style>

#CompanyProfile{
  opacity: 0;
}


</style>
