<div id="sideNav" class="col-xs-3 col-md-2 animated fadeInLeft">
  <ul class="sideLinks">
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-user-circle" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-envelope-open" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-sign-in" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-user-circle" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-envelope-open" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>  Users</a></li>
    <li><a href="Users.php" class="btn btn-success"><i class="fa fa-sign-in" aria-hidden="true"></i>  Users</a></li>
  </ul>
</div>
 
