<script src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="./assets/js/script.js"></script>

<div class="hamburger" id="hamburger-6">
  <span class="line"></span>
  <span class="line"></span>
  <span class="line"></span>
</div>

<div id="sideNav" class="col-xs-3 col-md-2" style="display:none;">
  <ul class="sideLinks">
    <li><a href="#" class="btn btn-success"><i class="fa fa-user-circle" aria-hidden="true"></i>  Users</a></li>
    <li><a href="#" class="btn btn-success" id="showhideAnalysis"><i class="fa fa-chevron-down" aria-hidden="true"></i> Analysis</a>
      <div id="charts" style="display:none;">
        <a href="wordmap.phtml" class="btn btn-success"><i class="fa fa-line-chart" aria-hidden="true"></i> sector</a>
        <a href="townStats.phtml" class="btn btn-success"><i class="fa fa-pie-chart" aria-hidden="true"></i> city</a>
        <a href="sectorStats.phtml" class="btn btn-success"><i class="fa fa-bar-chart" aria-hidden="true"></i> analysis</a>
      </div>
    </li>
    <li><a href="#" class="btn btn-success"><i class="fa fa-line-chart" aria-hidden="true"></i> Stability</a></li>
    <li><a href="#" class="btn btn-success" id="showhideCV"><i class="fa fa-chevron-down" aria-hidden="true"></i> CV</a>
      <div id="cvs" style="display:none;">
        <a href="#" class="btn btn-success"><i class="fa fa-line-chart" aria-hidden="true"></i> Tips</a>
        <a href="#" class="btn btn-success"><i class="fa fa-pie-chart" aria-hidden="true"></i> Uploading</a>
        <a href="#" class="btn btn-success"><i class="fa fa-bar-chart" aria-hidden="true"></i> Online</a>
      </div>
    </li>
        <li><a href="#" class="btn btn-success"><i class="fa fa-envelope" aria-hidden="true"></i> About</a></li>


  </ul>
</div>
<style>
.six {
  width: 49.2%;
}
#sideNav{
  background-color: black;
  position: absolute;
  display: inline-block;
  left: 0;
  padding: 0;
  height: 100%;
  background-color: #50505f;
}
.sideLinks{
  background-color: #41394c;
  color: white;
  text-decoration: none;
  list-style: none;
  padding-left: 0px;

}
.sideLinks> li > .btn-success:focus{
  background-color: #41394c !important;
}
.sideLinks a:hover {
background-color: #4e4e4c;
border: solid 0.004vh #b7c780;
border-left: solid 0.6vh #c3e42d;
}
.sideLinks li > a{
  width: 100%;
  border-radius: 0px;
  background-color: #50505f;
  border-size: 1px;
  border-width: 0;
  border-color: black;
  text-align: left;
  padding: 2vh 0px 2vh 3vh;
  border: solid #b7c790 0.002rem;
}
#charts a{
  width: 100%;
  border-radius: 0px;
  background-color: #50505f;
  border-size: 1px;
  border-width: 0;
  border-color: black;
  text-align: left;
  padding: 2vh 0px 2vh 3vh;
}
#charts a:hover{
  background-color: #4e4e4c;
  border: solid 0.004vh #b7c780;
  border-left: solid 0.6vh #c3eaaa;
}
#cvs a{
  width: 100%;
  border-radius: 0px;
  background-color: #50505f;
  border-size: 1px;
  border-width: 0;
  border-color: black;
  text-align: left;
  padding: 2vh 0px 2vh 3vh;
}
#cvs a:hover{
  background-color: #4e4e4c;
  border: solid 0.004vh #b7c780;
  border-left: solid 0.6vh #c3eaaa;
}

</style>
