<?php
require_once "header.phtml";
require_once "navAdmin.phtml";

?>
<link rel="stylesheet" href="./assets/css/adminStyle.css"/>
<link rel="stylesheet" href="z.css">
<link rel="stylesheet" href="./assets/css/bootstrap-select.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
<script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
<!-- <script src="./assets/js/bootstrap-select.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>




</script>

<body>

  <div class="container-fluid">
    <?php
    require_once "adminSideNav.phtml";
    ?>
    <form action="" class="col-xs-12" id="cityPicker">
          <select data-live-search="true" id="citySelect">



          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info">
    </form>




  </div>

</body>

<?php
require_once "footer.phtml";
?>
<script>


$(document).ready(function(){
  $.getJSON("./companiespercounty.php", function(data){
    var counties = data.map(function(element){
      return element.county
    })
    counties.forEach(function(element){
      $('#citySelect').append('<option val="'+ element +'">'+ element +'</option>');
    })
    console.log(counties);
   });
  $('#cityPicker').on('submit', function(event){
    //prevent from submiting
    event.preventDefault();
    if($('#citySelect').val() != ''){
      var x = $(this).serialize();
      alert($('#citySelect').val());
    }
    else{
      alert("Please select a city.");
      return false;
    }

  });

  $('#cityPicker').keyup(function(e){
    var input = e.target.value;
    if(input.length > 1){
      getListOfCompaniesByCounty(input)
    }
  })


  function getListOfCompaniesByCounty(input){
   $.getJSON("./companiespercounty.php", function(data){
     var counties = data.map(function(element){
       return element.county
     })
     counties.forEach(function(element){
      $('#citySelect').append('<option val="'+ element +'">'+ element +'</option>');
     })
     console.log(counties);
    });
  }
});

</script>
