<?php
require_once "header.phtml";
require_once "navAdmin.phtml";

?>
<link rel="stylesheet" href="./assets/css/adminStyle.css"/>
<link rel="stylesheet" href="z.css">
<link rel="stylesheet" href="./assets/css/bootstrap-select.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
<script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
<!-- <script src="./assets/js/bootstrap-select.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>




</script>

<body>

  <div class="container-fluid">
    <?php
    require_once "adminSideNav.phtml";
    ?>
    <form action="" class="col-xs-12" id="cityPicker">
          <select class="selectpicker" data-live-search="true" id="citySelect">
            <option value="d">d</option>
            <option value="cc">cc</option>
            <option value="aa">aa</option>
            <option value="qq">qq</option>
            <option value="qqc">qqc</option>
          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info">
    </form>




  </div>

</body>

<?php
require_once "footer.phtml";
?>
<script>


$(document).ready(function(){
  $('#cityPicker').on('submit', function(event){
    //prevent from submiting
    event.preventDefault();
    if($('#citySelect').val() != ''){
      var x = $(this).serialize();
      alert($('#citySelect').val());
    }
    else{
      alert("Please select a city.");
      return false;
    }
  });
});

</script>
