<?php
require_once "header.phtml";
require_once "navAdmin.phtml";

?>
<link rel="stylesheet" href="./assets/css/adminStyle.css"/>
<link rel="stylesheet" href="z.css">
<link rel="stylesheet" href="./assets/css/bootstrap-select.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
<script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
<!-- <script src="./assets/js/bootstrap-select.min.js"></script> -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>

<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
crossorigin="anonymous"></script>


</script>

<body>

  <div class="container-fluid">
    <?php
    require_once "adminSideNav.phtml";
    ?>
    <form action="./industryPerCounty.php" class="col-xs-12" id="cityPicker" method="post">
          <select class="from-control input-sm" id="citySelect">
            <option value="">Select County</option>
          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info">
    </form>

    <div class="chart-container">
      <div class="pie">
        <canvas id="pie" width="100vw" height="50vh" class="scrollable"></canvas>
      </div>
    </div>




  </div>

</body>

<?php
require_once "footer.phtml";
?>
<script>


$(document).ready(function(){

  $.getJSON("./companiespercounty.php", function(data){
    var counties = data.map(function(element){
      return element.county
    })
    counties.forEach(function(element){
      $('#citySelect').append('<option val="'+ element +'">'+ element +'</option>');
    })
    console.log(counties);
   });
  $('#cityPicker').on('submit', function(event){
    //prevent from submiting
    event.preventDefault();
    var that = $(this);
    var url = that.attr('action');
    var type = that.attr('method');
    var cdata = {};
    cdata.county = $('#citySelect').val();
    if($('#citySelect').val() != ''){
    $.ajax({
      url: url,
      type: type,
      data: cdata,
      success: function(response){
        var d = response;
        var pp = [];
        var qq = [];
        for (var i=1; i<d.length; i++) {
         pp.push( d[i].industry);
        }
        for (var j=1; j<d.length; j++) {
         qq.push( d[j].num);
        }
        var chartData = {
          labels: pp,
          datasets : [
            {
              label : 'Companies',
              backgroundColor: 'rgba(185, 179, 193, 1)',
              borderWidth: 0.5,
              hoverBackgroundColor: 'rgba(156, 93, 93, 0.75)',
              data: qq,
            }

          ]

        }
        var pie = $('#pie');
        var pie = new Chart(pie, {
          type: "radar",
          data: chartData
          ,
          options:{
            title:{
              display: true,
              text: 'Industires in region',
              fontFamily: 'Robato',
              fontColor: '#000',
              defaultFontColor: 'black',	
              fontWeight: 'normal'
            },
                legend:{
                  display: false
                },
                tooltips: {
                  fontFamily: 'Dosis'
                }
              }
        });
      }


    });

    }
    else{
      alert("Please select a city.");
      return false;
    }

  });

  $('#cityPicker').keyup(function(e){
    var input = e.target.value;
    if(input.length > 1){
      getListOfCompaniesByCounty(input)
    }
  })


  function getListOfCompaniesByCounty(input){
   $.getJSON("./companiespercounty.php", function(data){
     var counties = data.map(function(element){
       return element.county
     })
     counties.forEach(function(element){
      $('#citySelect').append('<option val="'+ element +'">'+ element +'</option>');
     })
     console.log(counties);
    });
  }
});

</script>
<script src="industryPerCountyChart.js">


</script>
