<?php require_once "header.phtml"; ?>
    <div class="well col-sm-6 col-sm-offset-3 fade" id="userProfile">

        <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">


            <div class="form-group">
                <label for="email" class=" control-label">First Name</label>
                <input type="text" name="First_Name" value="<?php echo $Current_User['First_Name'];?>" class="form-control half">
            </div>
            <div class="form-group">
                <label for="email" class=" control-label">Last Name</label>
                <input type="text" name="Last_Name" value="<?php echo $Current_User['Last_Name'];?>" class="form-control half" >
            </div>
            <div class="form-group">
                <label for="email" class=" control-label">User Name</label>
                <input type="text" name="Username" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>

            <div class="form-group">
                <label for="address_line1" class=" control-label">Address line1</label>
                <input type="text" name="address_line1" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>

            <div class="form-group">
                <label for="address_line2" class=" control-label">Address line2</label>
                <input type="text" name="address_line2" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>

            <div class="form-group">
                <label for="postcode" class=" control-label">Postcode</label>
                <input type="text" name="postcode" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>

            <div class="form-group">
                <label for="phone" class=" control-label">Phone</label>
                <input type="text" name="phone" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>

            <div class="form-group">
                <label for="email" class=" control-label">Email</label>
                <input type="email" name="email" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>

            <div class="form-group">
                <label for="dateofbirth" class=" control-label">Date of birth</label>
                <input type="text" name="dateofbirth" value="<?php echo $Current_User['Username'];?>" class="form-control half" >
            </div>
            <div class="form-group">
              <label for="degree_id" class=" control-label">Highest Degree Level</label>
            <select name="degree_id" id="" class="form-control half">
              <option value="1">Bachelor</option>
              <option value="2">Masters</option>
              <option value="3">Phd</option>
            </select>
          </div>


            <div class="form-group">
                <label for="password" class=" control-label">Password</label>
                <input type="password" name="Password" value="" class="form-control half" >
            </div>
            <br>
            <br>
            <button type="submit" name="Usubmit" class="btn btn-info Brown center">Update</button>
            <a href="./admin-panel.php" class="btn btn-warning Brown center">Back to Dashboard</a>

        </form>

        <?php echo $view->result; ?>

    </div>
    <script>
    $(document).ready(function(){
    TweenLite.fromTo($('#userProfile'),1.7,{y: -100, rotationY: "-=160",ease: "Power4.easeOut"}, {y:100,opacity:1,rotationY: "0",ease: "Power4.easeOut"});
    });
    </script>
