<?php
require_once "header.phtml";
require_once "navAdmin.phtml";
require_once "adminSideNav.phtml";


$theQuery = "insert into company (company_name,company_website,town,county,main_tier,subtier,industry,date_added,location_id) VALUES ('zzz','www.google.com','Salford','Manchester','Tier 2','Tier 2','Fintech','2018-04-23','200')";

 ?>
 <div class="container-fluid">

<link rel="stylesheet" href="./assets/css/stylesheet.css">
 <link rel="stylesheet" href="z.css">

    <div class="well col-sm-6 col-sm-offset-3" id="userProfile">

        <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">

<div class="col-xs-5">

  <div class="form-group">
      <label for="email" class=" control-label">First Name</label>
      <input type="text" name="First_Name" value="<?php echo $Current_User['First_Name'];?>" class="form-control circle">
  </div>
  <div class="form-group">
      <label for="email" class=" control-label">User Name</label>
      <input type="text" name="Username" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>
  <div class="form-group">
      <label for="address_line1" class=" control-label">Address line1</label>
      <input type="text" name="address_line1" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>
  <div class="form-group">
      <label for="address_line2" class=" control-label">Address line2</label>
      <input type="text" name="address_line2" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>
  <div class="form-group">
      <label for="postcode" class=" control-label">Postcode</label>
      <input type="text" name="postcode" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>
  <div class="form-group">
      <label for="dateofbirth" class=" control-label">Date of birth</label>
      <input type="text" name="dateofbirth" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>

  <div class="form-group">
    <label for="degree_id " class=" control-label">Highest Degree Level</label>
    <select name="degree_id" id="" class="form-control">
      <option value="1">Bachelor</option>
      <option value="2">Masters</option>
      <option value="3">Phd</option>
    </select>
  </div>

</div>
<div class="col-xs-1"></div>
<div class="col-xs-5">
  <div class="form-group">
      <label for="email" class=" control-label">Last Name</label>
      <input type="text" name="Last_Name" value="<?php echo $Current_User['Last_Name'];?>" class="form-control circle" >
  </div>










  <div class="form-group">
      <label for="email" class=" control-label">Email</label>
      <input type="email" name="email" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>

  <div class="form-group">
      <label for="phone" class=" control-label">Phone</label>
      <input type="text" name="phone" value="<?php echo $Current_User['Username'];?>" class="form-control circle" >
  </div>

  <div class="form-group">
      <label for="password" class=" control-label">Password</label>
      <input type="password" name="Password" value="" class="form-control circle" >
  </div>
  <button type="submit" name="Usubmit" class="btn btn-info Brown center">Update</button>
  <a href="./admin-panel.php" class="btn btn-warning Brown center">Back to Dashboard</a>
</div>



        </form>

        <?php echo $view->result; ?>

    </div>
</div>
    <script>
    $(document).ready(function(){
    TweenLite.fromTo($('#userProfile'),5.7,{y: -50, rotationX: "-=30",rotationY: "-=30",ease: "Power4.easeOut"}, {y:50,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
    });
    </script>
<style>

#userProfile{
  opacity: 0;
  border-radius: 0px;
  background-color: rgba(255,255,255,0.3);
}
</style>


<?php

require_once "footer.phtml";

?>
