<?php
require_once "header.phtml";
require_once "navAdmin.phtml";

?>


  <title>Stats</title>
  <link rel="stylesheet" href="./assets/css/adminStyle.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.css">
  <script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.11/crossfilter.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>




</head>
<body>
  <div class="container-fluid">
    <?php
    require_once "adminSideNav.phtml";
    ?>
  </div>

<div class="chart-container col-xs-12">
  <div class="pie">
    <canvas id="pie" width="100vw" height="50vh" class="scrollable"></canvas>
  </div>
</div>


</body>

<script src="qqq.js">


</script>


<style>

.county{
  background-color: blue;
}

</style>

</html>

<link rel="stylesheet" href="z.css">

<?php
require_once "footer.phtml";
?>
