<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js"></script>
  <title>SVG</title>
</head>
<body>
  <!-- <svg width="400" height="400" style="background: black;"></svg> -->
  <div id="element">




  </div>
  <script type="text/javascript">
    d3.select('#element')
        .append('svg')
         .attr('width', 400)
         .attr('height', 400)
         .style('background', '#9f2c2c');

  </script>
</body>
</html>
