<?php
require_once "header.phtml";
require_once "navAdmin.phtml";
require_once "adminSideNav.phtml";
?>


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Stats</title>
  <link rel="stylesheet" href="./assets/css/adminStyle.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.css">
  <script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.11/crossfilter.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.js"></script>


</head>
<body>
<!-- <img src="./ukmap.svg" alt="" width="80%" height="80%"> -->
<!-- <img src="./ukmap2.svg" alt="" width="80%" height="80%"> -->

<div id="Companies" width="100%"></div>
<svg id="canvas" height="600px" width="1200px"></svg>


</body>


<script>
 var companiesNum = dc.rowChart("#Companies");
  d3.json("./companiesPerCounty.php", function (err,data) {

  if(err) throw err;
  var ndx = crossfilter(data);
  var all = ndx.groupAll();
   var county = ndx.dimension(function (d) {return d["county"] ;} );
   var companies = ndx.dimension( function (d) {return d['companies'];} );
   var g = companies.group();
    companiesNum.height(1700).dimension(companies).group(g).data(function(group) { return group.top(170); });
    console.log(companies);
    dc.renderAll();

    });





</script>



<style>

.county{
  background-color: blue;
}

</style>

</html>



<?php
require_once "footer.phtml";
?>
