<?php
require_once "header.phtml";
require_once "navAdmin.phtml";
require_once "adminSideNav.phtml";
?>


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Stats</title>
  <link rel="stylesheet" href="./assets/css/adminStyle.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.css">
  <script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.11/crossfilter.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>




</head>
<body>
<!-- <img src="./ukmap.svg" alt="" width="80%" height="80%"> -->
<!-- <img src="./ukmap2.svg" alt="" width="80%" height="80%"> -->

<div id="Companies" ></div>
<div id="Counties" ></div>
<div class="chart-container">
  <div class="pie">
    <canvas id="pie" width="1100vw" height="500px" class="scrollable"></canvas>
  </div>
</div>

<svg id="canvas" height="600px" width="1200px"></svg>


</body>


<script>
 var companiesNum = dc.rowChart("#Companies");
  var countiesNum = dc.rowChart("#Counties");
  d3.json("./companiesPerCounty.php", function (err,data) {

  if(err) throw err;
  var ndx = crossfilter(data);
  var all = ndx.groupAll();
   var county = ndx.dimension(function (d) {return d["county"] ;} );
   var companies = ndx.dimension( function (d) {return d['companies'];} );
   var g = companies.group();
   console.log(g);
    companiesNum.height(1200).width(1300).dimension(county).group(g).data(function(group) { return group.top(170); });
    countiesNum.height(1200).width(1300).dimension(companies).group(g).data(function(group) { return group.top(170); });
    console.log(companies);
    dc.renderAll();

    });
    $.getJSON("./companiesPerCounty.php", function(d){
      var pp = [];
      var qq = [];
      for (var i=1; i<50; i++) {
       pp.push( d[i].town);
      }
      for (var j=1; j<50; j++) {
       qq.push( d[j].companies);
      }
      var chartData = {
        labels: pp,
        datasets : [
          {
            label : 'Companies',
            backgroundColor: 'rgba(100, 200, 200, 0.75)',
            borderColor: 'rgba(230, 2, 200, 0.75)',
            hoverBackgroundColor: 'rgba(156, 93, 93, 0.75)',
            data: qq
          }
        ]
      }
      var pie = $('#pie');
      var pie = new Chart(pie, {
        type: "bar",
        data: chartData
      });
      console.log(d["companies"]);
    });




</script>



<style>

.county{
  background-color: blue;
}

</style>

</html>



<?php
require_once "footer.phtml";
?>
