<?php
require_once "header.phtml";
require_once "navAdmin.phtml";
require_once "adminSideNav.phtml";
?>


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Stats</title>
  <link rel="stylesheet" href="./assets/css/adminStyle.css"/>
  <script type="text/javascript" src="./assets/js/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js"></script>

</head>
<body>








</body>


<script>


d3.json("./companiesPerCounty.php", function (data) {

    var convas = d3.select("body").append("svg")
    .attr("width", 900)
    .attr("height", 900)

    convas.selectAll("rect")
    .data(data)
    .enter()
      .append("rect")
      .attr("width", function(d){ return d.companies; })
      .attr("height", 12)
      .attr("y", function (d) { return d.county; })
      .attr("fill", "red")


  });





</script>

</html>



<?php
require_once "footer.phtml";
?>
