<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login Form</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="./assets/css/stylesheet.css">
  <link rel="stylesheet" href="./assets/css/animate.css">
</head>
<body>
    <div class="cover">
        <div class="bg">
        </div>
      </div>

    <div class="login animated fadeInDown">
      <div class="container">
          <div class="row">
              <div class="col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 animated bounceInUp">
                  <div class="panel panel-default loginForm" style="background-color: white;">
                      <div class="panel-heading">Login</div>
                      <div class="panel-body">
                          <form class="form-horizontal" role="form" method="POST" action="./admin-panel.php">
                              <div class=" form-group">
                                <img src="./assets/images/graph_loop.gif" alt="" class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4">
                              </div>
                              <div class="form-group">
                                  <label for="email" class="col-xs-3 control-label">User Name</label>

                                  <div class=" col-xs-9 col-md-7">
                                      <input id="email" class="form-control circle" name="Username" value="">
                                  </div>
                              </div>

                              <div class="form-group">
                                  <label for="password" class="col-xs-3 control-label">Password</label>

                                  <div class=" col-xs-9 col-md-7">
                                      <input id="password" type="password" class="form-control circle" name="Password">
                                      <br>
                                      <button type="submit" name="Lsubmit" class="btn btn-md btn-info circle">Login
                                      </button>
                                      <a href="./userRegister.phtml" class="btn btn-md btn-warning circle">Sign Up!</a>
                                  </div>
                              </div>


                              <div class="form-group">
                                  <div class="col-xs-12">

                                  </div>
                              </div>
                              <br>
                              <?php echo " $view->result"; ?>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
</body>

</html>
<!-- Latest compiled and minified JavaScript -->

<script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
