<script src="./assets/js/jquery-3.2.1.min.js"></script>
<script src="./assets/js/script.js"></script>
<div id="sideNav" class="col-xs-3 col-md-2 animated fadeInLeft">
  <ul class="sideLinks">
    <li><a href="#" class="btn btn-success"><i class="fa fa-user-circle" aria-hidden="true"></i>  Users</a></li>
    <li><a href="#" class="btn btn-success" id="showhide"><i class="fa fa-line-chart" aria-hidden="true"></i>  job-sector analysis</a>
      <div id="charts" style="display:none;">
        <a href="#" class="btn btn-success"><i class="fa fa-line-chart" aria-hidden="true"></i>  job-sector analysis</a>
      </div>
    </li>
    <li><a href="#" class="btn btn-success"><i class="fa fa-pie-chart" aria-hidden="true"></i> job-city analysis </a></li>
    <li><a href="#" class="btn btn-success"><i class="fa fa-envelope" aria-hidden="true"></i> Chat</a></li>


  </ul>
</div>
