<?php
require("Template/header.phtml");
require("Template/adminNav.phtml");
require("Template/adminSideNav.phtml");





?>
<script>
$('#hamburger-6').click(function(){
      $('.largeDataHandler').toggleClass('col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2',200);
});
TweenLite.fromTo($('#userProfile'),4.7,{y: 850, rotationX: "-=130",rotationY: "-=70",ease: "Power4.easeOut"}, {y:50,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
});
</script>
<div class="container-fluid">

           <div class="well col-sm-6 col-sm-offset-3 bluredSection fade" id="userProfile">

               <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">

                     <div class="form-group">
                       <label for="locationname" class=" control-label">Location Name</label>
                       <input type="text" name="Location_Name" class="form-control circle" id="locationname">
                     </div>
                     <div class="form-group">
                       <label for="longitude" class=" control-label">Longitude</label>
                       <input type="text" name="Longitude" class="form-control circle" id="longitude">
                     </div>
                     <div class="form-group">
                       <label for="latitude" class=" control-label">Latitude</label>
                       <input type="text" name="Latitude" class="form-control circle" id="latitude">
                     </div>

                     <button type="submit" name="Asubmit" class="btn btn-info circle">Add Location</button>
                     <a href="./adminDashboard.php" class="btn btn-warning circle">Back to Dashboard</a>
                     <br>
                     <br>
                         <?php echo $view->result; ?>
           </div>

         </form>


     </div>

<?php
require("Template/footer.phtml");
?>
