<?php
require('Template/header.phtml');
require('Template/adminNav.phtml');
require('Template/adminSideNav.phtml');
?>
 <div class="container-fluid">

      <div class="well col-sm-6 col-sm-offset-3 bluredSection fade" id="userProfile">

          <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">

                <div class="form-group">
                  <label for="email" class=" control-label">User Name</label>
                  <input type="text" name="Username" value="<?php echo $Current_User->getUserName();?>" class="form-control circle" >
                </div>

                <div class="form-group">
                  <label for="password" class=" control-label">Password</label>
                  <input type="password" name="Password" class="form-control circle" id="password">
                </div>
                <button type="submit" name="Usubmit" class="btn btn-info circle">Update</button>
                <a href="./adminDashboard.php" class="btn btn-warning circle">Back to Dashboard</a>
                <br>
                <br>
                    <?php echo $view->result; ?>
                </div>

          </form>


      </div>
      </div>
    </div>
      <script>
      $(document).ready(function(){
      TweenLite.fromTo($('#userProfile'),4.7,{y: 850, rotationX: "-=130",rotationY: "-=70",ease: "Power4.easeOut"}, {y:50,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
      });
      </script>
      <style>

      #userProfile{
      opacity: 0;
      border-radius: 0px;
      background-color: rgba(255,255,255,0.3);
      }
      </style>

<?php require('Template/footer.phtml');
?>
