<?php
require_once "./Views/Template/header.phtml";
require_once "./Views/Template/nav.phtml";
require_once "./Views/Template/sideNav.phtml";
?>

<link rel="stylesheet" href="./assets/css/userStyle.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
  <div class="container bluredSection">
        <form action="./Web_Service/industryGrowthPerYear.php" class="col-xs-12" id="cityPicker" method="post">
              <select class="from-control input-sm" id="citySelect">
                <option value="">Select Industry</option>
                <?php
                for($i=0;$i<sizeof($industries);$i++){
                  echo '<option value="' . $industries[$i]["Industry"] . '">' . $industries[$i]["Industry"] . '</option>';
                }
                ?>
        </select>
        <br>
        <br>
        <input type="submit" name="submit" class="btn btn-sm btn-info" hidden>
        </form>
        <form action="./Web_Service/industryGrowthPerYear.php" class="col-xs-12" id="cityPicker2" method="post">
              <select class="from-control input-sm" id="citySelect2">
                <option value="">Select Industry</option>
                <?php
                for($i=0;$i<sizeof($industries);$i++){
                  echo '<option value="' . $industries[$i]["Industry"] . '">' . $industries[$i]["Industry"] . '</option>';
                }
                ?>
              </select>
              <br>
              <br>


        </form>

    <div class="chart-container col-xs-12" style="position:reletive;">

        <canvas id="chart" width="100vw" height="50vh"></canvas>

    </div>

    </div>

<?php
require_once "./Views/Template/footer.phtml";
?>
<script src="./assets/js/compundIndustryPerYear.js"></script>
