<?php
require("Template/header.phtml");
require("Template/adminNav.phtml");
require("Template/adminSideNav.phtml");
?>
<div class="container-fluid">


     <div class="well col-sm-6 col-sm-offset-3 bluredSection fade" id="userProfile">

         <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">

               <div class="col-xs-5">

               <div class="form-group">
                 <label for="Locaitonname" class=" control-label">Location Name</label>
                 <input type="text" name="Location_Name" value="<?php echo $Current_Location->getLocationName();?>" class="form-control circle" id="Locaitonname">
               </div>
               <div class="form-group">
                 <label for="Latitude" class=" control-label">Latitude</label>
                 <input type="text" name="Latitude" value="<?php echo $Current_Location->getLocationLatitude();?>" class="form-control circle" id="Latitude">
               </div>
               <div class="form-group">
                 <label for="longitude" class=" control-label">Longitude</label>
                 <input type="text" name="Longitude" value="<?php echo $Current_Location->getLocationLongitude();?>" class="form-control circle" id="longitude">
               </div>
               <input type="hidden" name="Location_Id" value="<?php echo $Current_Location->getLocationId();?>">
               <button type="submit" name="Usubmit" class="btn btn-success circle">Update Locaiton</button>

               <a href="./adminDashboard.php" class="btn btn-warning circle">Back to Dashboard</a>

                   <?php echo $view->result; ?>
               </div>

         </form>




     </div>
     </div>
   </div>
     <script>
     $(document).ready(function(){
     TweenLite.fromTo($('#userProfile'),4.7,{y: 850, rotationX: "-=130",rotationY: "-=70",ease: "Power4.easeOut"}, {y:50,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
     });
     </script>
     <style>

     #userProfile{
     opacity: 0;
     border-radius: 0px;
     background-color: rgba(255,255,255,0.3);
     }
     </style>
<?php
require("Template/footer.phtml");
?>
