<?php
require_once "./Views/Template/header.phtml";
require_once "./Views/Template/nav.phtml";
require_once "./Views/Template/sideNav.phtml";
?>

  <link rel="stylesheet" href="./assets/css/userStyle.css"/>
  <link rel="stylesheet" href="./assets/css/ham.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
  <div class="container">

  <div class="container bluredSection">
    <form action="./Web_Service/industryPerCounty.php" class="col-xs-12 fade" id="cityPicker" method="post">
          <select class="from-control input-sm" id="citySelect">
            <option value="">Select County</option>
          </select>
          <select class="from-control input-sm" id="chartType">
            <option value="">Select Chart Type</option>
            <option value="bar">Bar</option>
            <option value="doughnut">Doughnut</option>
            <option value="pie">Pie</option>
            <option value="polarArea">Polar Area</option>
          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info" hidden>
    </form>

    <div class="chart-container col-xs-12">

        <canvas id="chart" class="fade"></canvas>

    </div>

    </div>

  </div>


<script src="./assets/js/industriesPerCountyChart.js"></script>
<?php
require_once "./Views/Template/footer.phtml";
?>
