<?php
require_once "./Views/Template/header.phtml";
require_once "./Views/Template/nav.phtml";
require_once "./Views/Template/sideNav.phtml";


?>
<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
<link rel="stylesheet" href="./assets/css/userStyle.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>

  <div class="container-fluid">
  <div class="container bluredSection">
    <form action="./industryPerCounty.php" class="col-xs-12" id="cityPicker" method="post">
          <select class="from-control input-sm" id="citySelect">
            <option value="">Select County</option>
          </select>
          <select class="from-control input-sm" id="chartType" hidden>
            <option value="">Select Chart Type</option>
            <option value="radar" selected="selected">Radar</option>
          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info" hidden>
    </form>
    <form action="./industryPerCounty.php" class="col-xs-12" id="cityPicker2" method="post">
          <select class="from-control input-sm" id="citySelect2">
            <option value="">Select County</option>
          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info" hidden>
    </form>
    <div class="chart-container col-xs-12">

        <canvas id="pie"></canvas>

    </div>

    </div>




  </div>

</body>

<?php
require_once "./Views/Template/footer.phtml";
?>
<script src="./assets/js/industriesInCounties.js"></script>
