<?php
require_once "./Views/Template/header.phtml";
require_once "./Views/Template/nav.phtml";
require_once "./Views/Template/sideNav.phtml";
?>

  <link rel="stylesheet" href="./assets/css/userStyle.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>

  <div class="container bluredSection">

    <form action="./Web_Service/industryGrowthPerYear.php" class="col-xs-12 fade" id="cityPicker" method="POST">
      <select class="from-control input-sm" id="citySelect">
          <option value="">Select Industry</option>
      <?php

              for($i=0;$i<sizeof($industries);$i++){
                echo '<option value="'. $industries[$i]['Industry'] . '">'. $industries[$i]['Industry']  .'</option>';
              }

      ?>

          </select>
    </form>


    <div class="chart-container col-xs-12">

        <canvas id="chart" class="fade" width="100vw" height="60vh"></canvas>

    </div>

    </div>

  </div>



<?php
require_once "./Views/Template/footer.phtml";
?>
<script src="./assets/js/industryPerYear.js"></script>
<link rel="stylesheet" href="./assets/css/ham.css">
