<?php
require_once "./Views/Template/header.phtml";
require_once "./Views/Template/nav.phtml";
require_once "./Views/Template/sideNav.phtml";
?>

  <link rel="stylesheet" href="./assets/css/userStyle.css"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>

  <div class="container">

    <form action="./Web_Service/industryGrowthPerYear.php" class="col-xs-12 fade" id="cityPicker" method="POST">
      <select class="from-control input-sm" id="citySelect">
          <option value="">Select Industry</option>
      <?php

              for($i=0;$i<sizeof($indstries);$i++){
                echo '<option value="'. $indstries[$i]['Industry'] . '">'. $indstries[$i]['Industry']  .'</option>';
              }

      ?>

          </select>

          <input type="submit" name="submit" class="btn btn-sm btn-info" hidden>
    </form>
   <?php




   ?>








    <form action="./Web_Service/industryPerCounty.php" class="col-xs-12 fade" id="cityPicker" method="POST">
          <select class="from-control input-sm" id="citySelect">
            <option value="">Select Industry</option>
          </select>
          <select class="from-control input-sm" id="chartType">
            <option value="">Select Chart Type</option>
            <option value="bar">Bar</option>
            <option value="doughnut">Doughnut</option>
            <option value="pie">Pie</option>
            <option value="polarArea">Polar Area</option>
          </select>
          <br>
          <br>
          <input type="submit" name="submit" class="btn btn-sm btn-info" hidden>
    </form>

    <div class="chart-container col-xs-12">

        <canvas id="pie" class="fade" width="100vw" height="60vh"></canvas>

    </div>

    </div>

  </div>



<?php
require_once "footer.phtml";
?>
<script src="./assets/js/industriesPerYear.js"></script>
<link rel="stylesheet" href="./assets/css/ham.css">
