<?php
require("Template/header.phtml");
require("Template/adminNav.phtml");
require("Template/adminSideNav.phtml");
?>
<script>
$('#hamburger-6').click(function(){
      $('.largeDataHandler').toggleClass('col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2',200);
});
</script>

        <div class="container-fluid">
          <div class="col-xs-12 largeDataHandler">
           <table id="outdatedCompaniesTable" class="table table-hover table-bordered table-responsive">
           <thead>
             <tr class="centerText">
               <td>Company Name</td>
               <td>Edit</td>
               <td>Delete</td>
             </tr>

           </thead>
            <?php

             foreach ($companyList as $company){
                     echo '<tr class="centerText" >

                     <td>'. (($company->getCompanyName())?$company->getCompanyName():"Not Found") .  '</td>
                     <td>'. '<form action="./editCompany.php" method="POST">
                             <input type="hidden" name="Company_Id" value="'. $company->getCompanyId() .'">
                             <button class="btn btn-md btn-info circle" type="submit" name="outdatedEsubmit">Edit Company </button>
                             </form>'  .
                     '</td>'.'
                     <td>'. '<form action="'. $_SERVER['PHP_SELF'] .'" method="POST">
                             <input type="hidden" name="Company_Id" value="'. $company->getCompanyId() .'">
                             <button class="btn btn-md btn-danger circle" type="submit" name="Dsubmit">Delete Company </button>
                             </form>'  .
                     '</td>'
                     ;
             }
            ?>
           </table>
          </div>
          <div class="row">
            <form action="<?php $_SERVER['PHP_SELF'] ?>" method="GET" class="col-xs-2 col-xs-offset-5">
                <button type="submit" class="btn btn-md btn-info circle" name="page">Next</button>
            </form>
          </div>
        </div>


















<?php
require("Template/footer.phtml");
?>
