<?php
require('Template/header.phtml');
?>
<script>
$(document).ready(function(){
TweenLite.fromTo($('.signUpForm'),2.7,{z: -1150, rotationX: "+=120",rotationY: "+=10",ease: "Power4.easeOut"}, {y:150,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
});
</script>
    <div class="login">
      <div class="container-fluid">
          <div class="row">
              <div class="col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4">
                  <div class="panel panel-default signUpForm fade">
                      <div class="panel-heading">Sign Up</div>
                      <div class="panel-body">
                          <form class="form-horizontal" role="form" method="POST" action="<?php echo $_SERVER['PHP_SELF']; ?>">


                              <div class="form-group">
                                  <label for="Username" class="col-xs-3 control-label">Username</label>

                                  <div class=" col-xs-9 col-md-7">
                                      <input id="username" class="form-control circle" name="Username" value="" required>
                                  </div>
                              </div>
                              <div class="form-group">
                                  <label for="email" class="col-xs-3 control-label">Email Address</label>

                                  <div class=" col-xs-9 col-md-7">
                                      <input type="email" id="email" class="form-control circle" name="Email" value="" required>
                                  </div>
                              </div>

                              <div class="form-group">
                                  <label for="password" class="col-xs-3 control-label">Password</label>

                                  <div class=" col-xs-9 col-md-7">
                                      <input id="password" type="password" class="form-control circle" name="Password" required>
                                      <br>
                                      <button type="submit" name="Rsubmit" class="btn btn-md btn-success circle">sign up
                                      </button>
                                      <a href="./Login.php" class="btn btn-md btn-info circle">Back to login</a>
                                  </div>
                              </div>
                              <input type="hidden" name="Is_Admin" value="0">
                              <br>
                              <?php echo " $view->result"; ?>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
    <?php
    require('Template/footer.phtml');
    ?>
