<?php
require_once("Template/header.phtml");
require_once("Template/adminNav.phtml");
require_once("Template/adminSideNav.phtml");
?>




        <div class="container-fluid">
          <div class="col-xs-12 largeDataHandler">
           <table id="outdatedCompaniesTable" class="table table-hover table-bordered table-responsive fade">
           <thead>
             <tr class="centerText">
               <td>Location Name</td>
               <td>Longitude</td>
               <td>Latitude</td>
               <td>Edit</td>
               <td>Delete</td>
             </tr>

           </thead>
            <?php

             foreach ($locationList as $location){
                     echo '<tr class="centerText" >

                     <td>'. (($location->getlocationName())?$location->getlocationName():"Not Found") .  '</td>
                     <td>'. (($location->getlocationName())?$location->getlocationLongitude():"Not Found") .  '</td>
                     <td>'. (($location->getlocationName())?$location->getlocationLatitude():"Not Found") .  '</td>
                     <td>'. '<form action="./editLocation.php" method="POST">
                             <input type="hidden" name="Location_Id" value="'. $location->getLocationId() .'">
                             <button class="btn btn-md btn-warning circle" type="submit" name="editLocationSubmit">Edit Location </button>
                             </form>'  .
                     '</td>
                     <td>'. '<form action="'. $_SERVER['PHP_SELF'] .'" method="POST">
                             <input type="hidden" name="Location_Id" value="'. $location->getLocationId() .'">
                             <button class="btn btn-md btn-danger circle" type="submit" name="Dsubmit">Delete Location </button>
                             </form>'  .
                     '</td>'
                     ;
             }

            ?>
           </table>

          </div>
          <div class="row">
            <form action="<?php $_SERVER['PHP_SELF'] ?>" method="GET" class="col-xs-2 col-xs-offset-5">
                <button type="submit" class="btn btn-md btn-info circle" name="page">Next</button>
            </form>
          </div>
        </div>













<script>
$('#hamburger-6').click(function(){
      $('.largeDataHandler').toggleClass('col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2',200);
});
$(document).ready(function(){
TweenLite.fromTo($('#outdatedCompaniesTable'),6.7,{z: -350, rotationX: "+=30",rotationY: "+=10",ease: "Power4.easeOut"}, {y:50,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
});
</script>


<?php
require_once("Template/footer.phtml");
?>
