<?php
require_once "header.phtml";
require_once "./Views/Template/guideSideNav.phtml";
?>

    <title>Display a map</title>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js'></script>
     <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet' />
     <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.1/mapbox-gl-geocoder.min.js'></script>
     <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.1/mapbox-gl-geocoder.css' type='text/css' />
     <link rel="stylesheet" href="./assets/css/mapStyle.css">
     <div id='map' class="bluredSection"></div>
     <script src="./assets/js/tier2MapScript.js"></script>

<?php
require('Template/footer.phtml');
?>
