<?php
require_once "header.phtml";
require_once "./Views/Template/guideSideNav.phtml";
?>


<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Display a map</title>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js'></script>
     <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet' />
     <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.1/mapbox-gl-geocoder.min.js'></script>
     <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.1/mapbox-gl-geocoder.css' type='text/css' />
     <link rel="stylesheet" href="./assets/css/adminStyle.css"/>
     <link rel="stylesheet" href="z.css">
     <link rel="stylesheet" href="./assets/css/mapStyle.css">

    <div id='map' class="bluredSection"></div>

<script src="./assets/js/tier2MapScript.js"></script>

<?php
require_once "footer.phtml";
?>
<script>
$(document).ready(function(){
TweenLite.fromTo($('.mapboxgl-ctrl-geocoder'),2,{x:500}, {x:0,y:0,opacity: 1});

});
</script>
