<?php
require('Template/header.phtml');
require('Template/nav.phtml');
require('Template/sideNav.phtml');
?>
<script>
$('#hamburger-6').click(function(){
      $('#usersTable').toggleClass('col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2',200);
});
</script>
<div class="row">
    <div class="container-fluid text-center animated fadeIn" id="createAdmin">
        <div class="col-lg-12">
            <div class="panel">
                <div class="caption">
                    <button type="button" class="btn btn-primary circle" data-toggle="modal" data-target="#exampleModal">Add new Admin</button>
                </div>
            </div>
    </div>

    </div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content circle" id="AdminProfile">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Adding new Admin</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="padding-bottom: 50px">
                <form role="form" name="createForm" action="<?php $_SERVER["PHP_SELF"] ?>" method="POST">
                    <div class="form-group">
                        <label for="Username" class=" control-label">Username</label>
                        <input type="text" name="Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="Password" class=" control-label">Password</label>
                        <input type="text" name="Password" class="form-control" >
                    </div>
                    <button type="submit" name="Csubmit" class="btn btn-success btn-md circle">Add</button>
                    <button type="button" class="btn btn-danger black circle" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="container-fluid">

  <div class="col-xs-12 " id="users">
   <table id="usersTable" class="table table-hover table-bordered table-responsive">
   <thead>
     <tr class="centerText">

       <td>First Name</td>
       <td>Last Name</td>
       <td>Username</td>
       <td>Email</td>
       <td>Phone</td>
       <td>Postcode</td>
       <td>Date of Birth</td>
       <td>Degree</td>
       <td>Delete</td>

     </tr>

   </thead>
    <?php
     foreach ($view->userList as $user){
             echo '<tr class="centerText" >
             <td>'. $user->getFirstName() .  '</td>
             <td>'. $user->getLastName()  . '</td>
             <td>'. $user->getUsername()  . '</td>
             <td>'. $user->getEmail()     . '</td>
             <td>'. $user->getPhone()  . '</td>
             <td>'. $user->getPostcode()  . '</td>
             <td>'. $user->getDOB()     . '</td>
             <td>'. $user->getDegree()    . '</td>
             <td>'. '<form action="'. $_SERVER['PHP_SELF'] .'" method="POST">
                     <input type="hidden" name="User_id" value="'. $user->getUserId() .'">
                     <button class="btn btn-xs btn-danger circle" type="submit" name="Dsubmit">Delete ' . $user->getFirstName() . ' ' . $user->getLastName() .'</button>
                     </form>'  . '</td>'
             ;
     }
    ?>
   </table>
  </div>
</div>











    <ul>
        <?php foreach ($view->userList as $user) : ?>
            <li>
                <?php  echo $user->getAll();
                var_dump($user);
                 ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php require('Template/footer.phtml') ?>
<link rel="stylesheet" href="./assets/css/ham.css">
