<?php
require_once "./Views/Template/header.phtml";
require('./Views/Template/adminNav.phtml');
require('./Views/Template/adminSideNav.phtml');
?>
<link rel="stylesheet" href="./assets/css/ham.css">
<script>
$('#hamburger-6').click(function(){
      $('#usersTable').toggleClass('col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2',700);
});
</script>
<div class="row">
    <div class="container-fluid text-center" id="createAdmin">
        <div class="col-lg-12">
            <div class="panel">
                <div class="caption">
                    <button type="button" class="btn btn-primary circle" data-toggle="modal" data-target="#exampleModal">Add new Admin</button>
                </div>
            </div>
    </div>

    </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content circle" id="AdminProfile">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Adding new Admin</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="padding-bottom: 50px">
                <form name="addAdmin" action="<?php $_SERVER["PHP_SELF"] ?>" method="POST">
                    <div class="form-group">
                        <label for="username" class=" control-label">Username</label>
                        <input id="username" type="text" name="Username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password" class=" control-label">Password</label>
                        <input id="password" type="text" name="Password" class="form-control" >
                    </div>
                    <button type="submit" name="Asubmit" class="btn btn-success btn-md circle">Add</button>
                    <button type="button" class="btn btn-danger black circle" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="container-fluid">

  <div class="col-xs-12" id="users">
   <table id="usersTable" class="table table-hover table-bordered table-responsive fade scrollable">
   <thead>
     <tr class="centerText">
       <td>Role</td>
       <td>First Name</td>
       <td>Last Name</td>
       <td>Username</td>
       <td>Email</td>
       <td>Phone</td>
       <td>Postcode</td>
       <td>Date of Birth</td>
       <td>Degree</td>
       <td>Delete</td>

     </tr>

   </thead>
    <?php
     foreach ($view->userList as $user){
             echo '<tr class="centerText" >
             <td>'. (($user->ifAdmin()==1)?"Admin":"User").  '</td>
             <td>'. (($user->getFirstName())?$user->getFirstName():"Not Found") .  '</td>
             <td>'. (($user->getLastName())?$user->getLastName():"Not Found"). '</td>
             <td>'. (($user->getUsername())?$user->getUsername():"Not Found"). '</td>
             <td>'. (($user->getEmail())?$user->getEmail():"Not Found").'</td>
             <td>'. (($user->getPhone())?$user->getPhone():"Not Found").'</td>
             <td>'. (($user->getPostcode())?$user->getPostcode():"Not Found").'</td>
             <td>'. (($user->getDOB())?$user->getDOB():"Not Found").'</td>
             <td>'. (($user->getDegree())?$user->getDegree():"Not Found").'</td>
             <td>'. '<form action="'. $_SERVER['PHP_SELF'] .'" method="POST">
                     <input type="hidden" name="User_id" value="'. $user->getUserId() .'">
                     <button class="btn btn-xs btn-danger circle" type="submit" name="Dsubmit">Delete ' . $user->getFirstName() . ' ' . $user->getLastName() .'</button>
                     </form>'  .
             '</td>'
             ;
     }
    ?>
   </table>
  </div>
</div>



<?php require('./Views/Template/footer.phtml') ?>
