<?php
require_once "./Views/Template/header.phtml";
require_once "./Views/Template/nav.phtml";
require_once "./Views/Template/sideNav.phtml";
?>
 <div class="container-fluid">




      <div class="well col-sm-6 col-sm-offset-3 bluredSection fade" id="userProfile">

          <form class="form-horizontal" role="form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">

                <div class="col-xs-5">

                <div class="form-group">
                  <label for="email" class=" control-label">First Name</label>
                  <input type="text" name="First_Name" value="<?php echo $Current_User->getFirstName();?>" class="form-control circle">
                </div>
                <div class="form-group">
                  <label for="email" class=" control-label">User Name</label>
                  <input type="text" name="Username" value="<?php echo $Current_User->getUserName();?>" class="form-control circle" required>
                </div>
                <div class="form-group">
                  <label for="address_line1" class=" control-label">Address line1</label>
                  <input type="text" name="Address_Line1" value="<?php echo $Current_User->getAdd1();?>" class="form-control circle" id="address_line1">
                </div>
                <div class="form-group">
                  <label for="address_line2" class=" control-label">Address line2</label>
                  <input type="text" name="Address_Line2" value="<?php echo $Current_User->getAdd2();?>" class="form-control circle" id="address_line2">
                </div>
                <div class="form-group">
                  <label for="postcode" class=" control-label">Postcode</label>
                  <input type="text" name="Postcode" value="<?php echo $Current_User->getPostcode();?>" class="form-control circle" >
                </div>
                <div class="form-group">
                  <label for="dateofbirth" class=" control-label">Date of birth</label>
                  <input type="date" name="DOB" value="<?php echo $Current_User->getDOB();?>" class="form-control circle" id="dateofbirth">
                </div>

                <div class="form-group">
                <label for="degree" class=" control-label">Highest Degree Level</label>
                <select name="Degree" id="degree" class="form-control">
                  <option value="<?php echo $Current_User->getDegree(); ?>" selected><?php echo $Current_User->getDegree(); ?></option>
                  <option value="Bachelor">Bachelor</option>
                  <option value="Masters">Masters</option>
                  <option value="Phd">Phd</option>
                </select>
                </div>

                </div>
                <div class="col-xs-1"></div>
                <div class="col-xs-5">
                <div class="form-group">
                  <label for="lastname" class=" control-label">Last Name</label>
                  <input type="text" name="Last_Name" value="<?php echo $Current_User->getLastName();?>" class="form-control circle" id="lastname">
                </div>

                <div class="form-group">
                  <label for="email" class=" control-label">Email</label>
                  <input type="email" name="Email" value="<?php echo $Current_User->getEmail();?>" class="form-control circle" id="email">
                </div>

                <div class="form-group">
                  <label for="phone" class=" control-label">Phone</label>
                  <input type="text" name="Phone" value="<?php echo $Current_User->getPhone();?>" class="form-control circle" id="phone">
                </div>

                <div class="form-group">
                  <label for="password" class=" control-label">Password</label>
                  <input type="password" name="Password" value="" class="form-control circle" id="password" required>
                </div>
                <button type="submit" name="Usubmit" class="btn btn-info circle">Update</button>
                <a href="./Dashboard.php" class="btn btn-warning circle">Back to Dashboard</a>
                <br>
                <br>
                    <?php echo $view->result; ?>
                </div>

          </form>




      </div>
      </div>
    </div>
      <script>
      $(document).ready(function(){
      TweenLite.fromTo($('#userProfile'),4.7,{y: 850, rotationX: "-=130",rotationY: "-=70",ease: "Power4.easeOut"}, {y:50,opacity:1,rotationX: "0",rotationY: "0",ease: "Power4.easeOut"});
      });
      </script>
      <style>

      #userProfile{
      opacity: 0;
      border-radius: 0px;
      background-color: rgba(255,255,255,0.3);
      }
      </style>

<?php
require_once "./Views/Template/footer.phtml";
?>
