<div class="hamburger" id="hamburger-6">
  <span class="line"></span>
  <span class="line"></span>
  <span class="line"></span>
</div>

<div id="sideNav" class="col-xs-3 col-md-2" style="display:none;">
  <ul class="sideLinks">

    <li><a href="#" class="btn btn-sm" id="showhideACC"><i class="fa fa-chevron-down" aria-hidden="true"></i> Location</a>
      <div id="ACC" style="display:none;">
        <a href="./addNewLocation.php" class="btn btn-sm"><i class="fa fa-building" aria-hidden="true"></i> Add</a>
        <a href="./removeLocation.php" class="btn btn-sm"><i class="fa fa-building" aria-hidden="true"></i> Remove</a>
      </div>
    </li>
    <li><a href="#" class="btn btn-sm" id="showhideACC2"><i class="fa fa-chevron-down" aria-hidden="true"></i> Companies</a>
      <div id="ACC2" style="display:none;">
        <a href="./newlyAddedCompanies.php" class="btn btn-sm"><i class="fa fa-building" aria-hidden="true"></i> New</a>
        <a href="./outDatedCompanies.php" class="btn btn-sm"><i class="fa fa-building" aria-hidden="true"></i> Outdated</a>
        <!-- <a href="#" class="btn btn-sm"><i class="fa fa-bar-chart" aria-hidden="true"></i> Map</a> -->
      </div>
    </li>
    <li><a href="./Users.php" class="btn btn-sm"><i class="fa fa-user-circle" aria-hidden="true"></i> Users</a></li>
  </ul>
</div>
<link rel="stylesheet" href="./assets/css/sideNavStyle.css">
<link rel="stylesheet" href="./assets/css/ham.css">
