<div class="hamburger" id="hamburger-6">
  <span class="line"></span>
  <span class="line"></span>
  <span class="line"></span>
</div>

<div id="sideNav" class="col-xs-10 col-md-10 col-lg-3" style="display:none;">
  <ul class="sideLinks">
                    <li>

                      <a href="./Dashboard.php" class="btn btn-sm"><i class="fa fa-map-o" aria-hidden="true"></i> BackToDashboard</a>

                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(87, 247, 0, 0.23);"><i class="center" aria-hidden="true"></i> Number of Companies: 0-10</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(94, 247, 0, 0.53);"><i class="center" aria-hidden="true"></i> Number of Companies: 10-20</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(0, 246, 69, 0.88);"><i class="center" aria-hidden="true"></i> Number of Companies: 20-30</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(132, 242, 212, 0.39);"><i class="center" aria-hidden="true"></i> Number of Companies: 30-40</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(73, 245, 224, 0.53);"><i class="center" aria-hidden="true"></i> Number of Companies: 40-50</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(82, 150, 241, 0.43);"><i class="center" aria-hidden="true"></i> Number of Companies: 50-60</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(7, 19, 103, 0.53);"><i class="center" aria-hidden="true"></i> Number of Companies: 60-70</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(23, 94, 232, 0.87);"><i class="center" aria-hidden="true"></i> Number of Companies: 70-80</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(18, 5, 42, 0.44);"><i class="center" aria-hidden="true"></i> Number of Companies: 80-90</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(177, 24, 231, 0.42);"><i class="center" aria-hidden="true"></i> Number of Companies: 90-100</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(197, 4, 255, 0.4);"><i class="center" aria-hidden="true"></i> Number of Companies: 100-300</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(238, 14, 176, 0.53);"><i class="center" aria-hidden="true"></i> Number of Companies: 300-500</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(232, 106, 26, 0.43);"><i class="center" aria-hidden="true"></i> Number of Companies: 500-700</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(232, 156, 26, 0.67);"><i class="center" aria-hidden="true"></i> Number of Companies: 700-800</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(232, 245, 88, 0.68);"><i class="center" aria-hidden="true"></i> Number of Companies: 800-1000</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(255, 245, 0, 0.55);"><i class="center" aria-hidden="true"></i> Number of Companies: 1000-5000</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(254, 5, 0, 0.56);"><i class="center" aria-hidden="true"></i> Number of Companies: 5000-10000</a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(255, 5, 0, 0.78);"><i class="center" aria-hidden="true"></i> Number of Companies: 10000-15000</a>
                    </li>

  </ul>
</div>
<link rel="stylesheet" href="./assets/css/guideSideNav.css">
<link rel="stylesheet" href="./assets/css/ham.css">
