<div class="hamburger" id="hamburger-6">
  <span class="line"></span>
  <span class="line"></span>
  <span class="line"></span>
</div>

<div id="sideNav" class="col-xs-10 col-md-10 col-lg-3" style="display:none;">
  <ul class="sideLinks">
    <li><a href="./Dashboard.php" class="btn btn-sm"><i class="fa fa-map-o" aria-hidden="true"></i> BackToDashboard</a></li>
    <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
      <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
        <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
          <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
            <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
              <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
                <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>
                  <li><a href="#" class="btn btn-sm"><i class="center" aria-hidden="true"></i> Black Color : <0 Number of Companies <1000</a></li>


                    <li>
                        <a href="#" class="btn btn-sm" style="background-color: rgba(87, 247, 0, 0.43);"><i class="center" aria-hidden="true"></i> Number of Companies: 10</a>
                    </li>

                    <!-- 'rgba(87, 247, 0, 0.43)',
                    20,
                    'rgba(94, 247, 0, 0.53)',
                    30,
                    'rgba(0, 246, 69, 0.88)',
                    40,
                    'rgba(132, 242, 212, 0.63)',
                    50,
                    'rgba(73, 245, 224, 0.75)',
                    60,
                    'rgba(82, 150, 241, 0.76)',
                    70,
                    'rgba(7, 19, 103, 0.53)',
                    80,
                    'rgba(23, 94, 232, 0.87)',
                    90,
                    'rgba(18, 5, 42, 0.67)',
                    100,
                    'rgba(177, 24, 231, 0.48)',
                    300,
                    'rgba(197, 4, 255, 0.69)',
                    500,
                    'rgba(238, 14, 176, 0.79)',
                    700,
                    'rgba(232, 106, 26, 0.71)',
                    800,
                    'rgba(232, 156, 26, 0.77)',
                    1000,
                    'rgba(232, 245, 88, 0.99)',
                    5000,
                    'rgba(255, 245, 0, 0.91)',
                    10000,
                    'rgba(254, 5, 0, 0.66)',
                    15000,
                    'rgba(255, 5, 0, 1)'
'rgba(255, 5, 0, 1)' -->

  </ul>
</div>
<style>
.six {
  width: 49.2%;
}

#sideNav{
  background-color: black;
  position: absolute;
  display: inline-block;
  left: 0;
  padding: 0;
  height: 100%;
  background-color: #2f2f29;
  z-index: 1000;
  overflow-y: scroll;
}
.sideLinks{
  background-color: #191a1a;
  text-decoration: none;
  list-style: none;
  padding-left: 0px;

}
.sideLinks .btn-sm{
  color: rgba(255, 255, 255, 0.86) !important;
}
.sideLinks> li > .btn-success:focus{
  background-color: #41394c !important;
}
.sideLinks a:hover {
background-color: #5f6055;
border: solid 0.004vh #707070;
border-left: solid 0.6vh #f2ec9c;
}
.sideLinks li > a{
  width: 100%;
    color: rgba(#595959, 0.71) !important;
    border-radius: 0px;
    background-color: #191a1a;
    border-size: 1px;
    border-width: 0;
    border-color: black;
    text-align: left;
    padding: 2vh 0px 2vh 3vh;
    border-top: solid #f3ffed 0.1px;
    border-right: solid #f3ffed 0.1px;
    border-bottom: solid #f3ffed 0.1px;
    text-align: center;
}
#charts a{
  width: 100%;
  border-radius: 0px;
  background-color: #191a1a;
  border-size: 1px;
  border-width: 0;
  border-color: black;
  text-align: left;
  padding: 2vh 0px 2vh 3vh;
}
#charts a:hover{
  background-color: #ddefee;
  border: solid 0.004vh #383838;
  border-left: solid 0.3vh #383838;
}
#cvs a{
  width: 100%;
  border-radius: 0px;
  background-color: #ddefee;
  border-size: 1px;
  border-width: 0;
  border-color: black;
  text-align: left;
  padding: 2vh 0px 2vh 3vh;
}
#cvs a:hover{
  background-color: #ddefee;
  border: solid 0.004vh #b7c780;
  border-left: solid 0.6vh #c3eaaa;
}

</style>
<link rel="stylesheet" href="./assets/css/ham.css">
