
<div class="hamburger" id="hamburger-6">
  <span class="line"></span>
  <span class="line"></span>
  <span class="line"></span>
</div>

<div id="sideNav" class="col-xs-10 col-md-3 col-lg-2" style="display:none;">
  <ul class="sideLinks">
    <li><a href="#" class="btn btn-sm" id="showhideACC3"><i class="fa fa-chevron-down" aria-hidden="true"></i>  Single Analysis</a>
      <div id="ACC3" style="display:none;">
        <a href="./tier2Map.php" class="btn btn-sm"><i class="fa fa-line-chart" aria-hidden="true"></i> Tier 2 Companies on the map</a>
        <a href="./startupanalysis.phtml" class="btn btn-sm"><i class="fa fa-map-o" aria-hidden="true"></i> Static</a>
        <a href="industryAnalysis.phtml" class="btn btn-sm"><i class="fa fa-map" aria-hidden="true"></i> Interactive</a>
        <!-- <a href="sectorStats.phtml" class="btn btn-sm"><i class="fa fa-bar-chart" aria-hidden="true"></i> analysis</a> -->
      </div>
    </li>

    <li><a href="#" class="btn btn-sm" id="showhideACC"><i class="fa fa-chevron-down" aria-hidden="true"></i>  Industry Analysis</a>
      <div id="ACC" style="display:none;">
        <a href="./industryMap.php" class="btn btn-sm"><i class="fa fa-map-signs" aria-hidden="true"></i> Industry Map</a>
        <a href="./stabilityAnalysis.phtml" class="btn btn-sm"><i class="fa fa-map-pin" aria-hidden="true"></i> Stability</a>
        <a href="./startupanalysis.phtml" class="btn btn-sm"><i class="fa fa-map-o" aria-hidden="true"></i> StartUp</a>
        <!-- <a href="sectorStats.phtml" class="btn btn-sm"><i class="fa fa-bar-chart" aria-hidden="true"></i> analysis</a> -->
      </div>
    </li>

    <li><a href="#" class="btn btn-sm" id="showhideACC2"><i class="fa fa-chevron-down" aria-hidden="true"></i>  Compound Analysis</a>
      <div id="ACC2" style="display:none;">
        <a href="./industryAnalysis2.php" class="btn btn-sm"><i class="fa fa-line-chart" aria-hidden="true"></i> Line</a>
        <a href="./industryAnalysis3.php" class="btn btn-sm"><i class="fa fa-pie-chart" aria-hidden="true"></i> Radar</a>
        <!-- <a href="#" class="btn btn-sm"><i class="fa fa-bar-chart" aria-hidden="true"></i> Map</a> -->
      </div>
    </li>


  </ul>
</div>

<link rel="stylesheet" href="./assets/css/ham.css">
<link rel="stylesheet" href="./assets/css/sideNavStyle.css">
